version: '3.1'
services:
  pg_container:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: magalu_db
    ports:
      - "5432:5432"
    volumes:
      - ./PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/
    networks:
      - app-tier

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-tier

  backend:
    container_name: backend
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/backend
      - ./node_modules:/backend/node_modules
    ports:
      - "3000:3000"
    links:
      - pg_container
    depends_on:
      - pg_container
    networks:
      - app-tier
    restart: always
volumes:
  pg_data:

networks:
  app-tier:
    driver: bridge